version: '3'
services:

  producer-app:
    image: kafka-test/producer:latest
    environment:
      - KAFKA_TOPIC=patient
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=9092
      - KAFKA_SCHEMA_REGISTRY_HOST=schema-registry
      - KAFKA_SCHEMA_REGISTRY_PORT=8081
    depends_on:
      - kafka
      - schema-registry
    ports:
      - 8080:8080

  adapter-app:
    image: kafka-test/adapter:latest
    environment:
      - INBOUND_KAFKA_TOPIC=patient
      - INBOUND_KAFKA_BROKER_HOST=kafka
      - INBOUND_KAFKA_BROKER_PORT=9092
      - INBOUND_KAFKA_SCHEMA_REGISTRY_HOST=schema-registry
      - INBOUND_KAFKA_SCHEMA_REGISTRY_PORT=8081
      - OUTBOUND_KAFKA_TOPIC=patientAdministration
      - OUTBOUND_KAFKA_BROKER_HOST=kafka
      - OUTBOUND_KAFKA_BROKER_PORT=9092
    depends_on:
      - kafka
      - schema-registry

  consumer-app:
    image: kafka-test/consumer:latest
    environment:
      - TOPIC=patientAdministration
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=9092
    depends_on:
      - kafka
    ports:
      - 8082:8080
