version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOST_IP}:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092

  schema-registry:
    image: confluentinc/cp-schema-registry:5.1.0
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    depends_on:
      - zookeeper
    ports:
      - 8081:8081

  producer-app:
    image: kafka-test/producer:latest
    environment:
      - KAFKA_TOPIC=patient
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=9092
      - KAFKA_SCHEMA_REGISTRY_HOST=schema-registry
      - KAFKA_SCHEMA_REGISTRY_PORT=8081
    depends_on:
      - kafka
      - schema-registry
    ports:
      - 8080:8080

  adapter-app:
    image: kafka-test/adapter:latest
    environment:
      - INBOUND_KAFKA_TOPIC=patient
      - INBOUND_KAFKA_BROKER_HOST=kafka
      - INBOUND_KAFKA_BROKER_PORT=9092
      - INBOUND_KAFKA_SCHEMA_REGISTRY_HOST=schema-registry
      - INBOUND_KAFKA_SCHEMA_REGISTRY_PORT=8081
      - OUTBOUND_KAFKA_TOPIC=patientAdministration
      - OUTBOUND_KAFKA_BROKER_HOST=kafka
      - OUTBOUND_KAFKA_BROKER_PORT=9092
    depends_on:
      - kafka
      - schema-registry

  consumer-app:
    image: kafka-test/consumer:latest
    environment:
      - TOPIC=patientAdministration
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=9092
    depends_on:
      - kafka